# This is a basic workflow to deploy a git repository to Flywheel

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The following settings are used to configure the login details and SFTP path for deploying
    # a `wp-content` directory to sftp://sftp.flywheelsites.com/<site-owner>/<site-name>/wp-content
    env:
      # The folder in the git repository to upload to the SFTP server
      # Be sure this points to the `wp-content` folder
      # If the root of your repository is the contents of `wp-content`
      # (i.e. `themes` and `plugins` are top-level folders), use ./ here

      # SFTP_SOURCE: ./path/to/wp-content
      SFTP_SOURCE: ./

      # The Flywheel owner of the site to deploy to
      # Using an SFTP url of `sftp://sftp.flywheelsites.com/my-user-name/my-site-name/wp-content`,
      # you would set `SFTP_OWNER` to `my-user-name`

      # SFTP_OWNER: my-username
      # SFTP_OWNER: org-my-organization-name
      SFTP_OWNER: jarrodldavis

      # The site ID used to access the site's files in SFTP
      # Using an SFTP url of `sftp://sftp.flywheelsites.com/my-user-name/my-site-name/wp-content`,
      # you would set `SFTP_SITE` to `my-site-name`

      # SFTP_SITE: my-site-name
      SFTP_SITE: action-jackson

      # Your Flywheel username
      # Keep in mind that this is the username that *you* use to login to Flywheel and
      # may be different from the site's owner

      # SFTP_USER: my-username
      SFTP_USER: jarrodldavis

      # Be sure to also configure an `SFTP_PASSWORD` secret in your repository settings
      # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository

    # It is recommended to not modify any of the following configuration unless you know what you are doing.
    # To update your SFTP configuration, update the previous values under the `env` key.
    name: Deploy

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Deploys to FTP
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
        ftp-server: sftp://sftp.flywheelsites.com:22/${{ env.SFTP_OWNER }}/${{ env.SFTP_SITE }}/wp-content/

        # FTP account username
        ftp-username: ${{ env.SFTP_USER }}

        # FTP account password
        ftp-password: ${{ secrets.SFTP_PASSWORD }}

        # The local folder to copy, defaults to root project folder
        local-dir: ${{ env.SFTP_SOURCE }}

        # This was generated using the output of `ssh-keyscan sftp.flywheelsites.com`
        known-hosts: |
          sftp.flywheelsites.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMIS14tbLPD4QfBAd/0HR49FLqOnnJpFOQ1Oi1h+VJ2FORvREvaXkp7Dmwe2+V4lI2IRj/R5FQYgPeS/rEgo4WC9IGsCNNaKuInzEQXliWVmk83Qjvu7MHLH5f5Mi8rGwbZ15h+gD43hYkIWP2NqCORbqSKceljzoH6IMOk2uFeSciN5W4/UUGjGlCEPnde+PDHo/CpAacqvmNTRy/HjTr5ZVO+OPb1z39UXCSS7yuC5gVQV+fpAR6Qy6SxtDHZmj3oFrV2gnpit4W5n05gRTeN9t4yr7FVGHKyAK368rLnT/rzTKuXj1X0dqtJAgPc4x/1mGmlpGxFJyC81y68Nhb
          sftp.flywheelsites.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNUE6XSOzuPtV1OvxAWASIsQZVHh1MXcK4O9MXrNMdHotmXgi5k0PsaPnVoSak7HZXi1MrdYr/HUTCp2EeoBJwk=
          sftp.flywheelsites.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAvUkYak/VVuAvuYxO+8+yyNPf1B9K8qtaWLCfYnCo6p
